FROM ollama/ollama:latest

WORKDIR /models

# Copy only the Modelfile (not the .gguf)
COPY ./llm_llama/models/Modelfile /models/Modelfile

# Copy entrypoint script from repo root
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 11434

ENTRYPOINT ["/entrypoint.sh"]

